spring.application.name=online_learning
spring.datasource.url=jdbc:mysql://localhost:3306/online_learning?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Anithaj@2007
spring.jpa.hibernate.ddl-auto=update

